error.whitelabel.enabled: true

spring:
  application:
    name: Pracxs
    
  datasource:
    jndi-name: java:comp/env/jdbc/pracxs_angularjs
    
  jpa:
    generate-ddl: false
    database: MYSQL
    hibernate:
      ddl-auto: none
      
http:
  mappers:
    json-pretty-print: yes